---

    -   name: Add the user 'kafka'
        user:
            name: kafka
            shell: /bin/bash
            create_home: yes
            password: "{{ kafka_user_pass | password_hash('sha512') }}"
            # append: yes

    -   name: Add Kafaka to Sudoers
        copy:
            content: '%kafka ALL=(ALL:ALL) NOPASSWD:ALL'
            dest: /etc/sudoers.d/kafka_nopasswd
            mode: 0440

    -   name: Create the Downloads directory
        become: yes
        become_user: kafka
        file:
            path: "{{ item }}"
        loop:
            - ~/kafka
            - ~/Downloads

    -   name: Download Kafka
        become: yes
        become_user: kafka
        get_url:
            url: https://www.apache.org/dist/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz
            dest: ~/Downloads/kafka.tgz

    -   name: Extract Kafka 
        become: yes
        become_user: kafka
        unarchive:
            src: ~/Downloads/kafka.tgz
            dest: ~/kafka
            extra_opts: "--strip 1"

    -   name: Enable Topic Deletion
        become: yes
        become_user: kafka
        lineinfile:
            dest: ~/kafka/config/server.properties
            regexp: '^(.*)delete.topic.enable(.*)$'
            line: 'delete.topic.enable = true'
            state: present
    
    -   name: Sets systemd Zookeeper service
        become: yes
        become_user: kafka
        template:
            src: "zookeeper.service.j2"
            dest: "/etc/systemd/system/zookeeper.service"
    
    -   name: Sets systemd kafka service
        become: yes
        become_user: kafka
        template:
            src: "kafka.service.j2"
            dest: "/etc/systemd/system/kafka.service"

    -   name: enable service kafka and ensure it is started
        systemd:
            name: kafka
            enabled: yes
            state: started

